# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

logging:
  level:
    ROOT: error
    io.dereknelson.lostcities: debug
    org.hibernate: error
    org.springframework.web.filter.CommonsRequestLoggingFilter: error

spring:
  config:
    use-legacy-processing: true
  profiles:
    active: dev
    include:
      - swagger
      # Uncomment to activate TLS for the dev profile
      #- tls
  devtools:
    restart:
      enabled: true
      additional-exclude: static/**,.h2.server.properties
    livereload:
      enabled: false # we use Webpack dev server + BrowserSync for livereload
  jackson:
    serialization:
      indent-output: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: ${sm://accounts_database_url}
    username: ${sm://accounts_database_user}
    password: ${sm://accounts_database_password}
    hikari:
      poolName: Hikari
      auto-commit: true
  flyway:
    enabled: false
    url: ${sm://accounts_database_url}
    user: ${sm://accounts_database_user}
    password: ${sm://accounts_database_password}
    baseline-version: 0
    table: SCHEMA_VERSION
    check-location: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: update
  cloud.gcp.secretsmanager:
    enabled: true
    bootstrap: true
    credentials.encoded-key: ${SECRET_MANAGER_KEY:""}
    project-id: lostcities-cloud



  # mail:
  #   host: localhost
  #   port: 25
  #   username:
  #   password:
  messages:
    cache-duration: PT1S # 1 second, see the ISO 8601 standard
  thymeleaf:
    cache: false
  security:
    user:
      name: admin
      password: testing

hibernate:
  javax.cache:
    missing_cache_strategy: create

server:
  port: 8080
  forward-headers-strategy: framework

application:
  security:
    authentication:
      jwt:
        base64-secret: dGVzdGluZw==
