# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

logging:
  level:
    ROOT: debug
    io.dereknelson.lostcities: debug

spring:
  config:
    use-legacy-processing: true
  profiles:
    active: dev
    include:
      - swagger
      # Uncomment to activate TLS for the dev profile
      #- tls
  devtools:
    restart:
      enabled: true
      additional-exclude: static/**,.h2.server.properties
    livereload:
      enabled: false # we use Webpack dev server + BrowserSync for livereload
  jackson:
    serialization:
      indent-output: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://172.20.0.15:5432/lostcities-accounts
    username: accounts
    password: example
    hikari:
      poolName: Hikari
      auto-commit: true
  flyway:
    enabled: true
    url: jdbc:postgresql://172.20.0.15:5432/lostcities-accounts
    user: accounts
    password: example
    baseline-version: 0
    table: SCHEMA_VERSION
    check-location: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update




  # mail:
  #   host: localhost
  #   port: 25
  #   username:
  #   password:
  messages:
    cache-duration: PT1S # 1 second, see the ISO 8601 standard
  thymeleaf:
    cache: false
  security:
    user:
      name: admin
      password: testing

hibernate:
  javax.cache:
    missing_cache_strategy: create

server:
  port: 8080
  forward-headers-strategy: framework

application:
  security:
    authentication:
      jwt:
        base64-secret: dGVzdGluZw==
